# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/4a947ac1-0173-4fa5-a88b-0ae9666b5b1b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B485-3030";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/log" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/082f569e-a949-46ec-ad3c-13524d1fed46";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
