# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "nvme" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cf4e7b22-f771-471e-af57-457ddd65f1c9";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/b9fb5174-d700-4137-b43f-86c75f405568";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88B4-C126";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cf4e7b22-f771-471e-af57-457ddd65f1c9";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/log" =
    { device = "/dev/disk/by-uuid/cf4e7b22-f771-471e-af57-457ddd65f1c9";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cf4e7b22-f771-471e-af57-457ddd65f1c9";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/cf4e7b22-f771-471e-af57-457ddd65f1c9";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens160.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
